apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/crowdstrike-falcon/sre-assessment
    targetRevision: HEAD
    path: kubernetes/helm-charts/app
    helm:
      values: |
        replicaCount: 3
        image:
          repository: nginx
          tag: "1.25"
          pullPolicy: IfNotPresent
        service:
          type: ClusterIP
          port: 80
        ingress:
          enabled: true
          ingressClassName: nginx
          hosts:
            - host: app.sre-assessment.local
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - secretName: app-tls
              hosts:
                - app.sre-assessment.local
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 256Mi
        autoscaling:
          enabled: true
          minReplicas: 2
          maxReplicas: 10
          targetCPUUtilizationPercentage: 80
        serviceMonitor:
          enabled: true
          interval: 30s

  destination:
    server: https://kubernetes.default.svc
    namespace: sample-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true 